#!/bin/bash

# CREDENTIALS 
#USER=dummy@company.com
#ACCESS_TOKEN=access_token
#NAMESPACE=production-logs

# install the log main script
! whereis upstride-logs && \
curl https://raw.githubusercontent.com/UpStride/ops-scripts/main/upload-logs/main -o upstride-logs --silent > /dev/null && \
sudo mv upstride-logs /usr/bin &&\
chmod +x /usr/bin/upstride-logs 

# TEST CONFIGURATION
#! upstride-logs --dry-run && exit 2

# set the cronjob
# sudo cat > /etc/cron.hourly/upstride-logs <<EOL
##!/bin/bash
#/usr/bin/upstride-logs -u dummy@company.com -p access_token -n production-logs -c upstride-engine
#EOL
