#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  run -h registry_host -g google_drive -t access_token
  find all docker container into the registry and upload it to a google drive repository.
  Arguments:
   - h: registry host.
   - g: google drive folder ID ex: 1YWFivfLRgaGw1KTKUpR3B6uZc2Gbjg4w
   - t: google drive access token ex: ya29.a0ARrdaM90MMwDwRQAwVRLijn806-M_IVAPYBKl97eI0s7Niz0IzMyr1SMrxmUD5lItyNqhb-9hlJTVe49NVLJz2hCKztsgXCp45wgl4iA7Oysxr0iOuIlevGFpFs7bShjd5Ua13wWzgEIXMoJd0ifKdt5aZRP
  "
}

source "$(dirname $0)/shared/args.sh"

source "$(dirname $0)/shared/upload.sh"

echo -e "=== archive Registry"

echo -e "+ dependencies checks"

#Dependencies check
python3 --version >/dev/null 2>/dev/null || { echo -e "xxx missing dependency python3\n:  sudo apt install python3"; exit 2; }
docker --version >/dev/null 2>/dev/null || { echo -e "xxx missing dependency docker\n:  curl -fsSL https://get.docker.com | bash"; exit 2; }

#Env check
#[ -n "$REGISTRY_NAME" ] || { echo -e "xxx missing REGISTRY_NAME in the ENV. \nDo:\nexport REGISTRY_NAME=your.registry.name"; exit 2; }

echo -e "+ listing docker images"
LIST=$(python3 "$(dirname $0)/shared/scripts.py" list --host REGISTRY_HOST)

declare -i TOTAL=0

SUMMARY="summary.csv"

! [ -f $SUMMARY ] && echo "DOCKER,TARBALL,CHECKSUM" > $SUMMARY

echo -e "+ upload loop"

for DOCKER in ${LIST[*]}
  do
    grep -q "$DOCKER" $SUMMARY && echo " . skipping docker ... $DOCKER" && continue
    PARSED=$(sed 's/\:/%3A/g' <<< $(sed 's/\//%2F/g' <<<"$DOCKER"))
    echo -e " . pulling docker ... $DOCKER"
    docker pull $REGISTRY_HOST/$DOCKER > /dev/null
    echo -e " . building tarball ... $PARSED.tar"
    docker save $REGISTRY_HOST/$DOCKER -o $PARSED.tar
    echo -e " . uploading tarball ... $REGISTRY_NAME/$DOCKER"
    upload "$PARSED.tar"
    echo -e " . cleaning ... "
    echo "$REGISTRY_HOST/$DOCKER,$PARSED.tar,$(sha256sum $PARSED.tar|cut -d ' ' -f1)" >> $SUMMARY
    docker image rm "$REGISTRY_HOST/$DOCKER"  > /dev/null
    rm  "$PARSED.tar"
    TOTAL=$TOTAL+1
  done

echo -e "+ total=$TOTAL"

echo -e "+ pushing checksum file"
upload $SUMMARY
rm $SUMMARY

echo -e "=== exit"

