#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  run -u urls_list -d target_directory
  download youtube videos from urls.
  Arguments:
   - u: list of youtube urls txt file.
   - d: target directory
  "
}

source "$(dirname "$0")/shared/args.sh"

echo -e "=== download videos"

echo -e "+ dependencies check ..."

#Dependencies check
python --version >/dev/null 2>/dev/null || { echo -e "xxx missing dependency python3\n:  sudo apt install python"; exit 2; }
yt-dlp --version >/dev/null 2>/dev/null || { echo -e "xxx missing dependency youtube-dl\n:  pip install -U yt-dlp"; exit 2; }

#Check input

#Check Urls list
echo -e "+ urls check ..."
# shellcheck disable=SC2207
LIST=($(python "$(dirname $0)/shared/scripts.py" check --urls "$URLS"))

CWD=$PWD
# shellcheck disable=SC2153
directory=$(pwd "$DIRECTORY")
declare -i TOTAL=0

echo -e "+ download loop (do not interrupt)"
for url in ${LIST[*]}; do
  { cd "$directory" && yt-dlp -f "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "$url" >/dev/null && TOTAL=$TOTAL+1 ;} || cd "$CWD"
done
echo -e "+ total=$TOTAL"

echo -e "=== exit"
